
services:

  database:
    image: postgres:18-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - transcendence_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - transcendence_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - transcendence_network

networks:
  transcendence_network:
    driver: bridge

volumes:
  postgres_data: