
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ft-transcendence'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # backend
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'backend'

  # frontend
  - job_name: 'frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['frontend:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'frontend'

  # database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # system stats (cpu, mem, disk)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # container stats
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
